package pojo;
// Generated Sep 30, 2024 2:28:57 AM by Hibernate Tools 4.3.1


import DAO.DAOLayanan;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import javax.faces.bean.ManagedBean;

/**
 * Layanan generated by hbm2java
 */
@ManagedBean
public class Layanan  implements java.io.Serializable {


     private Integer idLayanan;
     private String namaLayanan;
     private String deskripsi;
     private BigDecimal hargaPerKilo;
     private Set transaksis = new HashSet(0);

    public Layanan() {
    }

	
    public Layanan(String namaLayanan, BigDecimal hargaPerKilo) {
        this.namaLayanan = namaLayanan;
        this.hargaPerKilo = hargaPerKilo;
    }
    public Layanan(String namaLayanan, String deskripsi, BigDecimal hargaPerKilo, Set transaksis) {
       this.namaLayanan = namaLayanan;
       this.deskripsi = deskripsi;
       this.hargaPerKilo = hargaPerKilo;
       this.transaksis = transaksis;
    }
    
    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;
        Layanan layanan = (Layanan) obj;
        return idLayanan == layanan.idLayanan;
    }

    @Override
    public int hashCode() {
        return Objects.hash(idLayanan);
    }
   
    public Integer getIdLayanan() {
        return this.idLayanan;
    }
    
    public void setIdLayanan(Integer idLayanan) {
        this.idLayanan = idLayanan;
    }
    public String getNamaLayanan() {
        return this.namaLayanan;
    }
    
    public void setNamaLayanan(String namaLayanan) {
        this.namaLayanan = namaLayanan;
    }
    public String getDeskripsi() {
        return this.deskripsi;
    }
    
    public void setDeskripsi(String deskripsi) {
        this.deskripsi = deskripsi;
    }
    public BigDecimal getHargaPerKilo() {
        return this.hargaPerKilo;
    }
    
    public void setHargaPerKilo(BigDecimal hargaPerKilo) {
        this.hargaPerKilo = hargaPerKilo;
    }
    public Set getTransaksis() {
        return this.transaksis;
    }
    
    public void setTransaksis(Set transaksis) {
        this.transaksis = transaksis;
    }

public void save() {
        DAOLayanan lyn = new DAOLayanan();
        lyn.addLayanan(this); // Simpan layanan ini
    }

    public List<Layanan> getAllRecords() {
        DAOLayanan lyn = new DAOLayanan();
        List<Layanan> llyn = lyn.retrieveTblLayanan();
        return llyn;
    }

    public void delete() {
        DAOLayanan plg = new DAOLayanan();
        plg.deleteLayanan(idLayanan);
        namaLayanan = "";
        deskripsi = "";
        hargaPerKilo = BigDecimal.ZERO;

    }

    public void update() {
        DAOLayanan plg = new DAOLayanan();
        plg.updateLayanan(this);
        namaLayanan = "";
        deskripsi = "";
        hargaPerKilo = BigDecimal.ZERO;

    }

    public String getbyid() {
        DAOLayanan plg = new DAOLayanan();
        Layanan layanan = plg.getById(idLayanan);
        if (layanan != null) {
            this.namaLayanan = layanan.getNamaLayanan();
            this.deskripsi = layanan.getDeskripsi();
            this.hargaPerKilo = layanan.getHargaPerKilo();
        } else {
            // Handle kasus ketika layanan tidak ditemukan
            this.namaLayanan = "";
            this.deskripsi = "";
            this.hargaPerKilo = BigDecimal.ZERO;
        }
        return null;
    }


}


