package pojo;
// Generated Sep 30, 2024 2:28:57 AM by Hibernate Tools 4.3.1

import DAO.DAOPelanggan;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;

/**
 * Pelanggan generated by hbm2java
 */
@ManagedBean
public class Pelanggan implements java.io.Serializable {

    private Integer idPelanggan;
    private String namaPelanggan;
    private String noTelepon;
    private Date tanggalDaftar;

    public Pelanggan() {
    }

    public Pelanggan(String namaPelanggan) {
        this.namaPelanggan = namaPelanggan;
    }

    public Pelanggan(String namaPelanggan, String noTelepon, Date tanggalDaftar) {
        this.namaPelanggan = namaPelanggan;
        this.noTelepon = noTelepon;
        this.tanggalDaftar = tanggalDaftar;
    }

    public Integer getIdPelanggan() {
        return this.idPelanggan;
    }

    public void setIdPelanggan(Integer idPelanggan) {
        this.idPelanggan = idPelanggan;
    }

    public String getNamaPelanggan() {
        return this.namaPelanggan;
    }

    public void setNamaPelanggan(String namaPelanggan) {
        this.namaPelanggan = namaPelanggan;
    }

    public String getNoTelepon() {
        return this.noTelepon;
    }

    public void setNoTelepon(String noTelepon) {
        this.noTelepon = noTelepon;
    }

    public Date getTanggalDaftar() {
        return this.tanggalDaftar;
    }

    public void setTanggalDaftar(Date tanggalDaftar) {
        this.tanggalDaftar = tanggalDaftar;
    }

    public void save() {
        DAOPelanggan plg = new DAOPelanggan();
        plg.addPelanggan(this);

    }

    public void delete() {
        DAOPelanggan plg = new DAOPelanggan();
        plg.deletePelanggan(idPelanggan);
        namaPelanggan = "";
        noTelepon = "";
        tanggalDaftar = null;

    }

    public void update() {
        DAOPelanggan plg = new DAOPelanggan();
        plg.updatePelanggan(this);
        namaPelanggan = "";
        noTelepon = "";
        tanggalDaftar = null;

    }

    public List<Pelanggan> getAllRecords() {
        DAOPelanggan plg = new DAOPelanggan();
        List<Pelanggan> lplg = plg.retrieveTblPelanggan();
        return lplg;
    }

    public String getbyid() {
        DAOPelanggan plg = new DAOPelanggan();
        List<Pelanggan> lPlg = (List<Pelanggan>) plg.getbyID(idPelanggan);
        namaPelanggan = lPlg.get(0).namaPelanggan;
        noTelepon = lPlg.get(0).noTelepon;
        tanggalDaftar = lPlg.get(0).tanggalDaftar;
        return null;
    }

}
