package pojo;
// Generated Sep 30, 2024 2:28:57 AM by Hibernate Tools 4.3.1

import DAO.DAOTransaksi;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;

/**
 * Transaksi generated by hbm2java
 */
@ManagedBean
public class Transaksi implements java.io.Serializable {

    private Integer idTransaksi;
    private Layanan layanan;
    private String namaPelanggan;
    private Date tanggalTransaksi;
    private BigDecimal totalBerat;
    private BigDecimal totalHarga;
    private String status;
    private String statusPembayaran;

    public Transaksi() {
    }

    public Transaksi(String namaPelanggan, Date tanggalTransaksi, BigDecimal totalBerat, BigDecimal totalHarga) {
        this.namaPelanggan = namaPelanggan;
        this.tanggalTransaksi = tanggalTransaksi;
        this.totalBerat = totalBerat;
        this.totalHarga = totalHarga;
    }

    public Transaksi(Layanan layanan, String namaPelanggan, Date tanggalTransaksi, BigDecimal totalBerat, BigDecimal totalHarga, String status, String statusPembayaran) {
        this.layanan = layanan;
        this.namaPelanggan = namaPelanggan;
        this.tanggalTransaksi = tanggalTransaksi;
        this.totalBerat = totalBerat;
        this.totalHarga = totalHarga;
        this.status = status;
        this.statusPembayaran = statusPembayaran;
    }

    public Integer getIdTransaksi() {
        return this.idTransaksi;
    }

    public void setIdTransaksi(Integer idTransaksi) {
        this.idTransaksi = idTransaksi;
    }

    public Layanan getLayanan() {
        return this.layanan;
    }

    public void setLayanan(Layanan layanan) {
        this.layanan = layanan;
    }

    public String getNamaPelanggan() {
        return this.namaPelanggan;
    }

    public void setNamaPelanggan(String namaPelanggan) {
        this.namaPelanggan = namaPelanggan;
    }

    public Date getTanggalTransaksi() {
        return this.tanggalTransaksi;
    }

    public void setTanggalTransaksi(Date tanggalTransaksi) {
        this.tanggalTransaksi = tanggalTransaksi;
    }

    public BigDecimal getTotalBerat() {
        return this.totalBerat;
    }

    public void setTotalBerat(BigDecimal totalBerat) {
        this.totalBerat = totalBerat;
    }

    public BigDecimal getTotalHarga() {
        return this.totalHarga;
    }

    public void setTotalHarga(BigDecimal totalHarga) {
        this.totalHarga = totalHarga;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStatusPembayaran() {
        return this.statusPembayaran;
    }

    public void setStatusPembayaran(String statusPembayaran) {
        this.statusPembayaran = statusPembayaran;
    }

    public void save() {
        DAOTransaksi trs = new DAOTransaksi();
        trs.addTransaksi(this);
    }

    public List<Transaksi> getAllRecords() {
        DAOTransaksi trs = new DAOTransaksi();
        List<Transaksi> ltrs = trs.retrieveTblTransaksi();
        return ltrs;
    }

    public void delete() {
        DAOTransaksi plg = new DAOTransaksi();
        plg.deleteTransaksi(idTransaksi);
        tanggalTransaksi = null;
        totalBerat = BigDecimal.ZERO;
        totalHarga = BigDecimal.ZERO;
        status = "";
        statusPembayaran = "";

    }

    public void update() {
        DAOTransaksi plg = new DAOTransaksi();
        plg.updateTransaksi(this);
        namaPelanggan = "";
        tanggalTransaksi = null;
        totalBerat = BigDecimal.ZERO;
        totalHarga = BigDecimal.ZERO;
        status = "";
        statusPembayaran = "";

    }

    public String getbyid() {
        DAOTransaksi plg = new DAOTransaksi();
        List<Transaksi> lPlg = plg.getbyID(idTransaksi);
        namaPelanggan = lPlg.get(0).namaPelanggan;
        tanggalTransaksi = lPlg.get(0).tanggalTransaksi;
        totalBerat = lPlg.get(0).totalBerat;
        totalHarga = lPlg.get(0).totalHarga;
        status = lPlg.get(0).status;
        statusPembayaran = lPlg.get(0).statusPembayaran;
        return null;
    }


}
